import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav";
import SubHeading from "@/components/subHeading";
import Link from 'next/link'

const saira = Saira({
  weight: "400",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.className} antialiased h-screen`}
      >
        <div className="md:px-24 py-4 md:gap-8 px-4 gap-4 h-full flex flex-col inline-block">
          <h1 className="text-6xl md:text-9xl drop-shadow-md"><Link href="/">James Cooper</Link></h1>
          <SubHeading />
          <Nav/>
          <main className="flex-grow overflow-y-auto flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
