import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav";
import SubHeading from "@/components/subHeading";
import Link from 'next/link'

const saira = Saira({
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.className} antialiased h-screen`}
      >
        <div className="p-8 pb-20 gap-16 sm:p-20 relative h-full">
          <h1 className="text-9xl drop-shadow-md"><Link href="/">James Cooper</Link></h1>
          <SubHeading />
          <Nav/>
          <main className="h-full w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
